FROM docker.elastic.co/beats/filebeat:6.2.4

COPY compose/filebeat.yml /usr/share/filebeat/filebeat.yml

COPY master_app.log /app/master_app.log 

COPY master_database.log /app/master_database.log

USER root

RUN chown filebeat /usr/share/filebeat/filebeat.yml

USER filebeat

RUN chmod go-w /usr/share/filebeat/filebeat.yml