FROM docker.elastic.co/beats/metricbeat:5.6.9

COPY compose/metricbeat.yml /usr/share/metricbeat/metricbeat.yml

USER root

RUN chown metricbeat /usr/share/metricbeat/metricbeat.yml

USER metricbeat

RUN chmod go-w /usr/share/metricbeat/metricbeat.yml