FROM docker.elastic.co/beats/heartbeat:6.2.4

COPY compose/heartbeat.yml /usr/share/heartbeat/heartbeat.yml

USER root

RUN chown heartbeat /usr/share/heartbeat/heartbeat.yml

USER heartbeat

RUN chmod go-w /usr/share/heartbeat/heartbeat.yml